/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Scene.gltf
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { gsap } from 'gsap';
import { useFrame, useThree } from '@react-three/fiber';

export function Scene(props) {
  const { nodes, materials } = useGLTF('/GLTFs/Scene.gltf')
  const {scene} = useThree();
  const {sceneVisible} = props
  const sceneRef = useRef();

  useFrame(({mouse}) => {
    props.orbitRef.current.setAzimuthalAngle(1.7+0.1*mouse.x)
    props.orbitRef.current.setPolarAngle(1.4+ 0.1*mouse.y)
  })

  useEffect(() => {
    console.log(sceneVisible)
    if(sceneVisible) Add();
    else Remove();
  }, [sceneVisible])

  const Remove = () => {
    sceneRef?.current?.traverse(child => {
      if(child.isMesh) {
        gsap.to(child.material, {
          transparent: true,
          opacity: 0,
          duration: 2,
          onComplete: () => {
            scene.remove(sceneRef.current)
          }
        })
      }
    })
  }

  const Add = () => {
    sceneRef?.current?.traverse(child => {
      if(child.isMesh) {
        scene.add(sceneRef.current)
        gsap.to(child.material, {
          transparent: false,
          opacity: 1,
          duration: 2,
        })
      }
    })
  }

  return (
    <group ref={sceneRef} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Orange} position={[-3.424, 4.653, 0]} scale={[0.558, 5.667, 5.667]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Blue} position={[-3.496, 0.126, -4.754]} scale={2.563} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Orange} position={[0.079, 0.243, 1.108]} scale={[4.933, 0.15, 4.933]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Light Blue']} position={[-2.057, 0.621, 4.939]} scale={[1.573, 0.442, 1.573]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Blue} position={[-4.44, 0.198, 5.285]} rotation={[0, 0, -Math.PI / 2]} scale={[3.733, 0.421, 3.733]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Currot} position={[0.836, 0.548, -3.599]} scale={[0.908, 0.26, 0.419]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Orange} scale={[14.394, 14.394, 25.993]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Orange} position={[-13.886, 14.422, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[14.394, 14.394, 25.665]} />
    </group>
  )
}

useGLTF.preload('/Scene.gltf')
